name: Generate Sitemap

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sundays
  workflow_dispatch:

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate and commit sitemap

    # IMPORTANT: Grant write permissions
    permissions:
      contents: write

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          # Use the GITHUB_TOKEN for authentication
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build site
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
        run: npx --no-install astro build

      - name: Generate the sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://www.reelikklemind.com/
          sitemap-path: public/sitemap.xml
          crawling-roots: "dist/"
          include-pdf: false

      - name: Commit sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-generate sitemap"
          file_pattern: public/sitemap.xml
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
