name: Build and Deploy

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sundays
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to GitHub Pages
    environment: github-pages

    # IMPORTANT: Grant write permissions
    permissions:
      contents: write

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          # Use the GITHUB_TOKEN for authentication
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Cache Node modules and npm
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ./tmp
            ./buildcache
            .astro
          key: build-cache-${{ github.run_id }}-${{ github.sha }}
          restore-keys: |
            build-cache-${{ github.run_id }}-
            build-cache-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build site
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          GITHUB_PAGES: true
          SITE: https://www.reelikklemind.com
          BASE: /
        run: npm run build

      - name: Generate search index
        run: npm run postbuild

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: ${{ secrets.CUSTOM_DOMAIN }}
